### ISSUE TITLE
docker - logstash cant find conf files

### ISSUE THREAD

**Issue by lcia-projects** [pfelk/docker#28]
i can get pfelk to run natively (not docker) just fine.. but i'd really prefer a docker installation. I've watched the youtube videos.. 

I get this error: logstash    | [INFO ] 2021-03-20 15:39:28.963 [Agent thread] configpathloader - No config files found in path {:path=>"/etc/pfelk/conf.d/*.conf"}

where do i need to put the folders for it to locate.. 
      - ./etc/logstash/config/:/usr/share/logstash/config:ro
      - ./etc/logstash/conf.d/:/etc/pfelk/conf.d:ro
      - ./etc/logstash/conf.d/patterns/:/etc/pfelk/patterns:ro
      - ./etc/logstash/conf.d/databases/:/etc/pfelk/databases:ro
so its my thinking that it should just look in your local folder where you pulled the git.  

where am i missing?

**Comment by a3ilson** [comment]
Thanks for the feedback! I added to my list of things to do and/or improve but will clarify in the future. To answer your question and forgive me if this is trivial:

The first portion is the location on your host followed by where within the docker container the files/folders will be accessible

This is my current setup:
```
- /etc/pfelk/config:/usr/share/logstash/config:ro
```
The `/etc/pfelk/config` is were the folder is on my actual host separated by `:` followed by where it needs to be for pfelk to work `/usr/share/logstash/config:ro`

invoking a `ls *` on my system results in the following where the path is `/etc/pfelk`:
```
conf.d:
01-inputs.conf  03-filter.conf  20-interfaces.conf  35-rules-desc.conf  45-cleanup.conf
02-types.conf   05-apps.conf    30-geoip.conf       36-ports-desc.conf  50-outputs.conf

config:
logstash.yml  pipelines.yml

databases:
private-hostnames.csv  rule-names.csv  service-names-port-numbers.csv

patterns:
openvpn.grok  pfelk.grok
```

This repository was defined for TravisCI to validate a working instance. I am using [this](https://raw.githubusercontent.com/pfelk/pfelk/main/docker-compose.yml) docker-compose.yml file.

**Comment by lcia-projects** [comment]
thank you for the quick response. to clarify. 

I need to make a folder in my host machine (server) /etc called "pfelk"
so.. /etc/pfelk

within that folder will be the files and folders listed in your response? 
i swore i tried that with no luck, but i'll try again. 

thanks again, great product, thank you for your hard work

**Comment by a3ilson** [comment]
Correct, all files are located within the `/etc/pfelk/` path:

```
etc/pfelk/
├── conf.d
│   ├── 01-inputs.conf
│   ├── 02-types.conf
│   ├── 03-filter.conf
│   ├── 05-apps.conf
│   ├── 20-interfaces.conf
│   ├── 30-geoip.conf
│   ├── 35-rules-desc.conf
│   ├── 36-ports-desc.conf
│   ├── 45-cleanup.conf
│   └── 50-outputs.conf
├── config
│   ├── logstash.yml
│   └── pipelines.yml
├── databases
│   ├── private-hostnames.csv
│   ├── rule-names.csv
│   └── service-names-port-numbers.csv
└── patterns
    ├── openvpn.grok
    └── pfelk.grok
```

**Comment by lcia-projects** [comment]
if thats the case.. how does that corrispond with whats in the docker-compose file:
...
```
logstash:
    container_name: logstash
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      LS_JAVA_OPTS: -Xmx1G -Xms1G
    restart: unless-stopped
    volumes:
      - ./etc/logstash/config/:/usr/share/logstash/config:ro       
      - ./etc/logstash/conf.d/:/etc/pfelk/conf.d:ro
      - ./etc/logstash/conf.d/patterns/:/etc/pfelk/patterns:ro
      - ./etc/logstash/conf.d/databases/:/etc/pfelk/databases:ro
```
i got it working but i had to change the "./etc/logstash/" to /etc/pfelk/...
